---
- name: install pbench-agent
  hosts: servers
  remote_user: tks
  gather_facts: no
  become: true
  # The default value ('production') can be overriddent by cenv, a host-specific
  # inventory variable.
  vars:
    pbench_configuration_environment: "{{ cenv | default('production') }}"

  roles:
    - wait_for_system
    - pbench_repo_install
    - pbench_agent_install
    - pbench_agent_config
    - ssh_key_exchange
    - run_test
  
