---
# tasks file for roles/run_test
- name: install uperf
  yum: 
    name: uperf
    state: present

- name: register tool
  become_user: root
  become_flags: "-i"
  shell: pbench-register-tool-set

- name: Run uperf and move results
  tags: run
  become_user: root
  become_flags: "-i"
  shell: nohup bash -c "pbench-uperf -t stream,rr -r 60 -m 64,16384 -p tcp -i 1,8,64 -C {{ groups['servers'][0] }} -S {{ groups['servers'][1] }} --max-stddev=10 </dev/null >/dev/null 2>&1  && pbench-move-results </dev/null >/dev/null 2>&1"  &
  async: 500
  poll: 0
  run_once: true

- debug:
    msg: "pbench-uperf -t stream,rr -r 60 -m 64,16384 -p tcp -i 1,8,64 -C {{ groups['servers'][0] }} -S {{ groups['servers'][1] }} --max-stddev=10 && pbench-move-results"
  run_once: true